[BE] 서비스 레이어에서의 인수 테스트 작성
ghojeong/baseball pull request #32
Opened 2021-05-07 17:00 UTC by malaheaven

안녕하세요 파이로! 말씀 주셨던 시나리오까지 금일 테스트 코드 작성을 완료했습니다.

해당 테스트 정말 면밀하고도 꼼꼼하게 검토해주시길 바랍니다.
시나리오를 생각하며 테스트 코드를 작성하는 게 생각보다 훨씬 더 어려운 작업이었습니다.

(잠깐 동안, 파이로를 아주 조금(?), 아주 조금보단 조금 더 많이(?) 원망했습니다 😢  
그런데 본 로직를 테스트 코드 없이 바로 작성했다면 
개발하다가 중간에 딴 길로 세거나 허둥지둥 할 것이란 생각에 아찔하더군요! 
역시, 테스트 코드를 작성하는 게 조금 더 안전한 길인 것 같습니다) 

각 시나리오 별 보내야하는 데이터가 맞는 지, 꼭 크로스 체크, 더블 체크 모두 부탁드리며~ 즐거운 코드 리뷰 부탁드립니당 👋 
덧, 혹시 몰라 추가되는 데이터는 주석을 조금 더 달아두었습니다. 참고하시길 바랍니다.

2021-05-08 00:48 UTC, ghojeong commented
> (잠깐 동안, 파이로를 아주 조금(?), 아주 조금보단 조금 더 많이(?) 원망했습니다

처음 TDD 를 하게 되면 겪게 되는 매우 정상적인 반응입니다.
다음주는 더 힘들테니 주말에 쉬면서 체력 보충해두세요!

2021-05-08 00:50 UTC, ghojeong commented
> Pitcher의 hit는 어떤의미인가? 피안타가 무엇인지 잘 모르겠다
> 평균을 도출하는 공식은 어떻게 되는것인가? 해당부분 잘 모르겠어서 일단 평균은 모두 0으로 처리했습니다

이런게 TDD 의 장점이죠. 프론트 분들에게 물어보러 갑시다.
위의 두 질문을 정리해서 Slack baseball 채널방에 물어봐주세요 @malaheaven 
질문하는게 감정적으로 부담스러우시면, 제가 질문을 올려보겠습니다.

다만 실제 현업에 가서도, 본인이 이렇게 용기내서 질문해야할 일이 많다는 점만 기억해두세요.
선임을 귀찮게 해서 혼나는 것은 한 순간이지만, 일을 잘못해서 혼나게 되면 진짜 엄청 괴로워집니다.

2021-05-08 00:54 UTC, ghojeong commented
> 질문하는게 감정적으로 부담스러우시면, 제가 질문을 올려보겠습니다.

오늘 저녁 8시까지 반응이 없으시면, 제가 질문을 올리도록 하겠습니다.
다만, 저는 개인적으로 로빈이 이런 질문을, 질문을 "정말로" 대답해 줄 수 있는 사람에게 찾아가서 물어보는 연습을 했으면 좋겠습니다.
("정말로"라는 말은 정답을 알고 있는 사람이 아니라, 틀리더라도 대답에 대해서 책임을 질 수 있는 사람을 말합니다. 기획자가 기획에 대해서 잘못 알고 있었다고 하면 변명의 여지가 없지요.)
가령 지금과 같은 경우는 만사이지요.

제가 프로젝트 매니저가 개판일 때는, 기획자와 따로 술을 먹으러 가야한다고 말했던 점 기억나시나요?

2021-05-08 03:06 UTC, malaheaven commented
@ghojeong 좋은 말씀 감사합니당~! 

> 다만 실제 현업에 가서도, 본인이 이렇게 용기내서 질문해야할 일이 많다는 점만 기억해두세요.
> 선임을 귀찮게 해서 혼나는 것은 한 순간이지만, 일을 잘못해서 혼나게 되면 진짜 엄청 괴로워집니다.

이번에 연습을 해봐야겠군여! ㅋㅋㅋㅋ 파이로한테 혼나지 않으려면요...ㅜ 흑흑(장난)
슬랙에 질문 올렸습니다 @ghojeong

2021-05-08 04:18 UTC, ghojeong requested changes
크로스 체크 중인데, 제가 의도한 대로 잘 작성해주신 것 같습니다.

> Pitcher의 hit는 어떤의미인가? 피안타가 무엇인지 잘 모르겠다
> 평균을 도출하는 공식은 어떻게 되는것인가? 해당부분 잘 모르겠어서 일단 평균은 모두 0으로 처리했습니다

모바일팀이 부분에 대한 답을 해주어서, 해당 부분이 반영되면 머지를 하도록 하겠습니다.
고생하셨습니다. 아마 모바일팀도 주말에는 답 안하고 푹 쉴 것 같으니깐,
로빈도 주말에 고생하지 마시고 푹 쉬세요 😎

2021-05-08 04:18 UTC, ghojeong commented on be/server/src/main/java/com/baseball/repository/MockedMatchInfoRepository.java
> +        //어웨이팀의 첫 이닝에서 Hit 가 나왔을 경우에 대한 스냅샷 테스트
스냅샷을 뜬 내용을 주석으로 남겨주셔서 감사합니다!
저도 덕분에 쉽게 확인이 가능하네요. 짱입니다 로빈! 👍

2021-05-08 04:23 UTC, malaheaven commented on be/server/src/main/java/com/baseball/repository/MockedMatchInfoRepository.java
> +        //어웨이팀의 첫 이닝에서 Hit 가 나왔을 경우에 대한 스냅샷 테스트
히히 감사합니다.. 주석을 다는게 말씀주신 고양이사진을 생각하면 안될거같았지만, 테스트 작성하다가 저도 혼란이 오는데 파이로도 혼란이 올 것으로 예상되어, 설명 주석을 작게나마 남겼습니다 😸 크로스체크 중에 빠진 내용 있으면 말씀주세용

2021-05-09 01:01 UTC, ghojeong approved these changes
예상 시나리오 문서까지 작성해주시다니, 엄청 감동입니다 로빈! 😍 
저도 체크를 해보았는데, 문제 되는 것 없어보입니다. 꼼꼼하시네요 로빈!
특히 예상 시나리오에서 무엇이 바뀌었는지 주석까지 적어주셔서, 체크를 하기 정말로 편했습니다.

>  주석을 다는게 말씀주신 고양이사진을 생각하면 안될거같았지만, 테스트 작성하다가 저도 혼란이 오는데 파이로도 혼란이 올 것으로 예상되어, 설명 주석을 작게나마 남겼습니다

정말로 감사합니다, 로빈!
고양이 이야기는 제가 겪었던 팀장님의 이야기이고,
저는 주석은 무조건 많이 적는게 좋다고 생각하는 편입니다.
불필요한 주석은 나중에라도 지울 수 있지만, 필요한 주석은 없으면 다시 작성하는데 머리가 터지니까요.
감사합니다 로빈 👍

2021-05-09 01:02 UTC, ghojeong commented
예상 시나리오 문서 확인하면서, json 형태 좀더 예쁘게 정렬도 해놓았습니다.
수고하셨습니다.

2021-05-09 01:02 UTC, merged